countries = {'Bolivia (Plurinational State of)':'Bolivia',
             'Democratic People\'s Republic of Korea':'North Korea',
             'Falkland Islands (Malvinas)':'Falkland Islands',
             'Iran (Islamic Republic of)':'Iran',
             'Kosovo[1]':'Kosovo',
             'Lao People\'s Democratic Republic':'Lao',
             'Micronesia (Federated States of)':'Micronesia',
             'Northern Mariana Islands (Commonwealth of the)':'Northern Mariana Islands',
             'Republic of Korea':'South Korea',
             'Syrian Arab Republic':'Syria',
             'Venezuela (Bolivarian Republic of)':'Venezuela',
             'occupied Palestinian territory, including east Jerusalem':'Palestine'}
